--2.1
SELECT *
FROM NHAN_VIEN AS NV INNER JOIN PHONG_BAN AS PB ON NV.PHG = PB.MaPHG
--2.2
SELECT TOP 1 WITH TIES MaNV, COUNT(MaDA)
FROM PHAN_CONG
GROUP BY MaNV
ORDER BY COUNT(MaDA) DESC
--2.3
SELECT *
FROM (	SELECT NV.MaNV, HoNV, TenNV, MaPHG, TenPHG, SUM(ThoiGian) AS TongTG
		FROM PHAN_CONG AS PC INNER JOIN NHAN_VIEN AS NV ON PC.MaNV = NV.MaNV INNER JOIN PHONG_BAN AS PB ON NV.PHG = PB.MaPHG
		GROUP BY NV.MaNV, HoNV, TenNV, MaPHG, TenPHG) AS TG
		WHERE TongTG = (	SELECT MAX(TongTG)
							FROM (	SELECT NV.MaNV, HoNV, TenNV, MaPHG, TenPHG, SUM(ThoiGian) AS TongTG
									FROM PHAN_CONG AS PC INNER JOIN NHAN_VIEN AS NV ON PC.MaNV = NV.MaNV INNER JOIN PHONG_BAN AS PB ON NV.PHG = PB.MaPHG
									GROUP BY NV.MaNV, HoNV, TenNV, MaPHG, TenPHG) AS TG1
							WHERE MaPHG = TG.MaPHG)